var OFM_CODES = {
  "AA": { "country": "Democratic Republic of the Congo", "source": "US State Dept OFM" },
  "AB": { "country": "Timor-Leste", "source": "US State Dept OFM" },
  "AC": { "country": "Cote d'Ivoire", "source": "US State Dept OFM" },
  "AD": { "country": "African Union", "source": "US State Dept OFM" },
  "AE": { "country": "Uzbekistan", "source": "US State Dept OFM" },
  "AF": { "country": "Japan", "source": "US State Dept OFM" },
  "AG": { "country": "Kosovo", "source": "US State Dept OFM" },
  "AH": { "country": "Madagascar", "source": "US State Dept OFM" },
  "AJ": { "country": "Panama", "source": "US State Dept OFM" },
  "AK": { "country": "Cape Verde", "source": "US State Dept OFM" },
  "AL": { "country": "South Sudan", "source": "US State Dept OFM" },
  "AQ": { "country": "Syria", "source": "US State Dept OFM" },
  "AU": { "country": "Uganda", "source": "US State Dept OFM" },
  "AV": { "country": "Israel", "source": "US State Dept OFM" },
  "AX": { "country": "Marshall Islands", "source": "US State Dept OFM" },
  "BL": { "country": "South Africa", "source": "US State Dept OFM" },
  "BV": { "country": "Solomon Islands", "source": "US State Dept OFM" },
  "BW": { "country": "World Bank", "source": "US State Dept OFM" },
  "CB": { "country": "Cambodia", "source": "US State Dept OFM" },
  "CC": { "country": "Ethiopia", "source": "US State Dept OFM" },
  "CG": { "country": "Marshall Islands", "source": "US State Dept OFM" },
  "CK": { "country": "Namibia", "source": "US State Dept OFM" },
  "CM": { "country": "Micronesia", "source": "US State Dept OFM" },
  "CN": { "country": "International Organization", "source": "US State Dept OFM" },
  "CS": { "country": "Afghanistan", "source": "US State Dept OFM" },
  "CT": { "country": "Bhutan", "source": "US State Dept OFM" },
  "CU": { "country": "Botswana", "source": "US State Dept OFM" },
  "CV": { "country": "Myanmar", "source": "US State Dept OFM" },
  "CW": { "country": "Cameroon", "source": "US State Dept OFM" },
  "CX": { "country": "Burundi", "source": "US State Dept OFM" },
  "CY": { "country": "China", "source": "US State Dept OFM" },
  "DA": { "country": "Colombia", "source": "US State Dept OFM" },
  "DB": { "country": "Costa Rica", "source": "US State Dept OFM" },
  "DC": { "country": "Cuba", "source": "US State Dept OFM" },
  "DD": { "country": "Cyprus", "source": "US State Dept OFM" },
  "DF": { "country": "Dominican Republic", "source": "US State Dept OFM" },
  "DG": { "country": "Ecuador", "source": "US State Dept OFM" },
  "DH": { "country": "Cote d'Ivoire", "source": "US State Dept OFM" },
  "DI": { "country": "South Africa", "source": "US State Dept OFM" },
  "DJ": { "country": "France", "source": "US State Dept OFM" },
  "DK": { "country": "Greece", "source": "US State Dept OFM" },
  "DL": { "country": "India", "source": "US State Dept OFM" },
  "DM": { "country": "Iran", "source": "US State Dept OFM" },
  "DN": { "country": "Denmark", "source": "US State Dept OFM" },
  "DP": { "country": "Bangladesh", "source": "US State Dept OFM" },
  "DR": { "country": "Slovakia", "source": "US State Dept OFM" },
  "DZ": { "country": "Palau", "source": "US State Dept OFM" },
  "FF": { "country": "Antigua and Barbuda", "source": "US State Dept OFM" },
  "FG": { "country": "Central African Republic", "source": "US State Dept OFM" },
  "FH": { "country": "Ireland", "source": "US State Dept OFM" },
  "FJ": { "country": "Lebanon", "source": "US State Dept OFM" },
  "FK": { "country": "Kenya", "source": "US State Dept OFM" },
  "FL": { "country": "Liberia", "source": "US State Dept OFM" },
  "FM": { "country": "Libya", "source": "US State Dept OFM" },
  "FN": { "country": "Malta", "source": "US State Dept OFM" },
  "FP": { "country": "Morocco", "source": "US State Dept OFM" },
  "FR": { "country": "Philippines", "source": "US State Dept OFM" },
  "FS": { "country": "Netherlands", "source": "US State Dept OFM" },
  "FT": { "country": "Qatar", "source": "US State Dept OFM" },
  "FV": { "country": "Sri Lanka", "source": "US State Dept OFM" },
  "FW": { "country": "Holy See", "source": "US State Dept OFM" },
  "FX": { "country": "Sierra Leone", "source": "US State Dept OFM" },
  "FZ": { "country": "Suriname", "source": "US State Dept OFM" },
  "GC": { "country": "Sweden", "source": "US State Dept OFM" },
  "GD": { "country": "Ukraine", "source": "US State Dept OFM" },
  "GG": { "country": "Zambia", "source": "US State Dept OFM" },
  "GN": { "country": "Turkey", "source": "US State Dept OFM" },
  "GP": { "country": "Albania", "source": "US State Dept OFM" },
  "GQ": { "country": "North Korea", "source": "US State Dept OFM" },
  "GX": { "country": "Vanuatu", "source": "US State Dept OFM" },
  "GY": { "country": "Chile", "source": "US State Dept OFM" },
  "HB": { "country": "Tonga", "source": "US State Dept OFM" },
  "HD": { "country": "Argentina", "source": "US State Dept OFM" },
  "HL": { "country": "Saint Lucia", "source": "US State Dept OFM" },
  "HM": { "country": "Andorra", "source": "US State Dept OFM" },
  "HN": { "country": "Mongolia", "source": "US State Dept OFM" },
  "HV": { "country": "Belgium", "source": "US State Dept OFM" },
  "HW": { "country": "Guatemala", "source": "US State Dept OFM" },
  "HX": { "country": "Benin", "source": "US State Dept OFM" },
  "HY": { "country": "Guinea-Bissau", "source": "US State Dept OFM" },
  "HZ": { "country": "Haiti", "source": "US State Dept OFM" },
  "JB": { "country": "Honduras", "source": "US State Dept OFM" },
  "JC": { "country": "Kuwait", "source": "US State Dept OFM" },
  "JD": { "country": "Mauritius", "source": "US State Dept OFM" },
  "JF": { "country": "Nigeria", "source": "US State Dept OFM" },
  "JG": { "country": "Portugal", "source": "US State Dept OFM" },
  "JH": { "country": "Somalia", "source": "US State Dept OFM" },
  "JJ": { "country": "Chad", "source": "US State Dept OFM" },
  "JK": { "country": "Turkey", "source": "US State Dept OFM" },
  "JM": { "country": "Yugoslavia", "source": "US State Dept OFM" },
  "JP": { "country": "Tunisia", "source": "US State Dept OFM" },
  "JQ": { "country": "Togo", "source": "US State Dept OFM" },
  "JS": { "country": "Slovenia", "source": "US State Dept OFM" },
  "JT": { "country": "Croatia", "source": "US State Dept OFM" },
  "JY": { "country": "Cyprus", "source": "US State Dept OFM" },
  "KB": { "country": "Monaco", "source": "US State Dept OFM" },
  "KD": { "country": "Eritrea", "source": "US State Dept OFM" },
  "KG": { "country": "Equatorial Guinea", "source": "US State Dept OFM" },
  "KH": { "country": "Hungary", "source": "US State Dept OFM" },
  "KJ": { "country": "Lithuania", "source": "US State Dept OFM" },
  "KK": { "country": "Fiji", "source": "US State Dept OFM" },
  "KL": { "country": "Jordan", "source": "US State Dept OFM" },
  "KM": { "country": "Jamaica", "source": "US State Dept OFM" },
  "KN": { "country": "Gabon", "source": "US State Dept OFM" },
  "KP": { "country": "Luxembourg", "source": "US State Dept OFM" },
  "KR": { "country": "Malaysia", "source": "US State Dept OFM" },
  "KS": { "country": "Mexico", "source": "US State Dept OFM" },
  "KU": { "country": "Sao Tome and Principe", "source": "US State Dept OFM" },
  "KV": { "country": "Saudi Arabia", "source": "US State Dept OFM" },
  "KW": { "country": "Seychelles", "source": "US State Dept OFM" },
  "KX": { "country": "Sudan", "source": "US State Dept OFM" },
  "LC": { "country": "Venezuela", "source": "US State Dept OFM" },
  "LD": { "country": "Vietnam", "source": "US State Dept OFM" },
  "LG": { "country": "Turkey", "source": "US State Dept OFM" },
  "LH": { "country": "Israel", "source": "US State Dept OFM" },
  "LJ": { "country": "Israel", "source": "US State Dept OFM" },
  "LK": { "country": "European Union", "source": "US State Dept OFM" },
  "LM": { "country": "North Macedonia", "source": "US State Dept OFM" },
  "LR": { "country": "Bosnia and Herzegovina", "source": "US State Dept OFM" },
  "LW": { "country": "Germany", "source": "US State Dept OFM" },
  "MF": { "country": "International Monetary Fund", "source": "US State Dept OFM" },
  "MK": { "country": "Djibouti", "source": "US State Dept OFM" },
  "MN": { "country": "Comoros", "source": "US State Dept OFM" },
  "MP": { "country": "Bahamas", "source": "US State Dept OFM" },
  "MW": { "country": "Maldives", "source": "US State Dept OFM" },
  "NA": { "country": "Oman", "source": "US State Dept OFM" },
  "NB": { "country": "Papua New Guinea", "source": "US State Dept OFM" },
  "NC": { "country": "Paraguay", "source": "US State Dept OFM" },
  "ND": { "country": "Romania", "source": "US State Dept OFM" },
  "NQ": { "country": "Angola", "source": "US State Dept OFM" },
  "NX": { "country": "Malaysia", "source": "US State Dept OFM" },
  "PA": { "country": "Austria", "source": "US State Dept OFM" },
  "PB": { "country": "Barbados", "source": "US State Dept OFM" },
  "PC": { "country": "Belize", "source": "US State Dept OFM" },
  "PD": { "country": "United Kingdom", "source": "US State Dept OFM" },
  "PF": { "country": "Bolivia", "source": "US State Dept OFM" },
  "PG": { "country": "Belarus", "source": "US State Dept OFM" },
  "PK": { "country": "Norway", "source": "US State Dept OFM" },
  "PL": { "country": "Chile", "source": "US State Dept OFM" },
  "PM": { "country": "Brunei", "source": "US State Dept OFM" },
  "PR": { "country": "Argentina", "source": "US State Dept OFM" },
  "PS": { "country": "Zimbabwe", "source": "US State Dept OFM" },
  "PV": { "country": "Republic of the Congo", "source": "US State Dept OFM" },
  "QD": { "country": "Burkina Faso", "source": "US State Dept OFM" },
  "QL": { "country": "St. Kitts and Nevis", "source": "US State Dept OFM" },
  "QM": { "country": "Bulgaria", "source": "US State Dept OFM" },
  "QN": { "country": "Laos", "source": "US State Dept OFM" },
  "QP": { "country": "Latvia", "source": "US State Dept OFM" },
  "QQ": { "country": "Lesotho", "source": "US State Dept OFM" },
  "QR": { "country": "Malawi", "source": "US State Dept OFM" },
  "QS": { "country": "Mozambique", "source": "US State Dept OFM" },
  "QT": { "country": "New Zealand", "source": "US State Dept OFM" },
  "QU": { "country": "Nicaragua", "source": "US State Dept OFM" },
  "QV": { "country": "Niger", "source": "US State Dept OFM" },
  "QW": { "country": "Poland", "source": "US State Dept OFM" },
  "QX": { "country": "Pakistan", "source": "US State Dept OFM" },
  "QY": { "country": "Yemen", "source": "US State Dept OFM" },
  "QZ": { "country": "Indonesia", "source": "US State Dept OFM" },
  "RB": { "country": "Rwanda", "source": "US State Dept OFM" },
  "RC": { "country": "St. Vincent and the Grenadines", "source": "US State Dept OFM" },
  "RD": { "country": "Senegal", "source": "US State Dept OFM" },
  "RL": { "country": "Uruguay", "source": "US State Dept OFM" },
  "RV": { "country": "San Marino", "source": "US State Dept OFM" },
  "SF": { "country": "Czech Republic", "source": "US State Dept OFM" },
  "SG": { "country": "Israel", "source": "US State Dept OFM" },
  "ST": { "country": "Dominica", "source": "US State Dept OFM" },
  "TF": { "country": "Algeria", "source": "US State Dept OFM" },
  "TG": { "country": "Canada", "source": "US State Dept OFM" },
  "TH": { "country": "Egypt", "source": "US State Dept OFM" },
  "TK": { "country": "Liechtenstein", "source": "US State Dept OFM" },
  "TL": { "country": "El Salvador", "source": "US State Dept OFM" },
  "TM": { "country": "Iceland", "source": "US State Dept OFM" },
  "TN": { "country": "Nepal", "source": "US State Dept OFM" },
  "TP": { "country": "Mauritania", "source": "US State Dept OFM" },
  "TQ": { "country": "Mali", "source": "US State Dept OFM" },
  "TR": { "country": "Italy", "source": "US State Dept OFM" },
  "TS": { "country": "Iraq", "source": "US State Dept OFM" },
  "TT": { "country": "Guyana", "source": "US State Dept OFM" },
  "TU": { "country": "Guinea", "source": "US State Dept OFM" },
  "TV": { "country": "Ghana", "source": "US State Dept OFM" },
  "TW": { "country": "Gambia", "source": "US State Dept OFM" },
  "TX": { "country": "Finland", "source": "US State Dept OFM" },
  "TY": { "country": "Grenada", "source": "US State Dept OFM" },
  "TZ": { "country": "Peru", "source": "US State Dept OFM" },
  "UA": { "country": "Bahrain", "source": "US State Dept OFM" },
  "UF": { "country": "Estonia", "source": "US State Dept OFM" },
  "UH": { "country": "Spain", "source": "US State Dept OFM" },
  "UX": { "country": "Trinidad and Tobago", "source": "US State Dept OFM" },
  "VF": { "country": "Thailand", "source": "US State Dept OFM" },
  "VG": { "country": "Tanzania", "source": "US State Dept OFM" },
  "VH": { "country": "Switzerland", "source": "US State Dept OFM" },
  "VJ": { "country": "Brazil", "source": "US State Dept OFM" },
  "VK": { "country": "Singapore", "source": "US State Dept OFM" },
  "VL": { "country": "Eswatini", "source": "US State Dept OFM" },
  "VM": { "country": "Nauru", "source": "US State Dept OFM" },
  "WB": { "country": "United Arab Emirates", "source": "US State Dept OFM" },
  "WD": { "country": "South Korea", "source": "US State Dept OFM" },
  "WM": { "country": "Samoa", "source": "US State Dept OFM" },
  "WZ": { "country": "United Kingdom", "source": "US State Dept OFM" },
  "XA": { "country": "Bangladesh", "source": "US State Dept OFM" },
  "XC": { "country": "Fiji", "source": "US State Dept OFM" },
  "XD": { "country": "Myanmar", "source": "US State Dept OFM" },
  "XE": { "country": "Ghana", "source": "US State Dept OFM" },
  "XF": { "country": "Turkey", "source": "US State Dept OFM" },
  "XG": { "country": "Norway", "source": "US State Dept OFM" },
  "XZ": { "country": "Australia", "source": "US State Dept OFM" },
  "YA": { "country": "Armenia", "source": "US State Dept OFM" },
  "YG": { "country": "Georgia", "source": "US State Dept OFM" },
  "YJ": { "country": "Tajikistan", "source": "US State Dept OFM" },
  "YK": { "country": "Kazakhstan", "source": "US State Dept OFM" },
  "YM": { "country": "Moldova", "source": "US State Dept OFM" },
  "YR": { "country": "Russia", "source": "US State Dept OFM" },
  "YT": { "country": "Turkmenistan", "source": "US State Dept OFM" },
  "YY": { "country": "Kyrgyzstan", "source": "US State Dept OFM" },
  "YZ": { "country": "Azerbaijan", "source": "US State Dept OFM" }
};

var PLATE_PREFIXES = { "D": "Diplomat", "S": "Staff", "C": "Consul" };

function lookupPlate(code) {
  code = code.toUpperCase().replace(/[^A-Z]/g, '');
  if (code.length < 2) return null;

  var prefix = null;
  var countryCode = null;

  if (code.length >= 3 && PLATE_PREFIXES[code[0]]) {
    prefix = PLATE_PREFIXES[code[0]];
    countryCode = code.substring(1, 3);
  } else {
    countryCode = code.substring(0, 2);
  }

  var entry = OFM_CODES[countryCode];
  if (!entry) return null;

  return { prefix: prefix, code: countryCode, country: entry.country, source: entry.source, fullCode: code };
}
