var OFM_CODES = {
  "AA": { "country": "Democratic Republic of the Congo", "flag": "🇨🇩", "source": "US State Dept OFM" },
  "AB": { "country": "Timor-Leste", "flag": "🇹🇱", "source": "US State Dept OFM" },
  "AC": { "country": "Cote d'Ivoire", "flag": "🇨🇮", "source": "US State Dept OFM" },
  "AD": { "country": "African Union", "source": "US State Dept OFM" },
  "AE": { "country": "Uzbekistan", "flag": "🇺🇿", "source": "US State Dept OFM" },
  "AF": { "country": "Japan", "flag": "🇯🇵", "source": "US State Dept OFM" },
  "AG": { "country": "Kosovo", "flag": "🇽🇰", "source": "US State Dept OFM" },
  "AH": { "country": "Madagascar", "flag": "🇲🇬", "source": "US State Dept OFM" },
  "AJ": { "country": "Panama", "flag": "🇵🇦", "source": "US State Dept OFM" },
  "AK": { "country": "Cape Verde", "flag": "🇨🇻", "source": "US State Dept OFM" },
  "AL": { "country": "South Sudan", "flag": "🇸🇸", "source": "US State Dept OFM" },
  "AQ": { "country": "Syria", "flag": "🇸🇾", "source": "US State Dept OFM" },
  "AU": { "country": "Uganda", "flag": "🇺🇬", "source": "US State Dept OFM" },
  "AV": { "country": "Israel", "flag": "🇮🇱", "source": "US State Dept OFM" },
  "AX": { "country": "Marshall Islands", "flag": "🇲🇭", "source": "US State Dept OFM" },
  "BL": { "country": "South Africa", "flag": "🇿🇦", "source": "US State Dept OFM" },
  "BV": { "country": "Solomon Islands", "flag": "🇸🇧", "source": "US State Dept OFM" },
  "BW": { "country": "World Bank", "source": "US State Dept OFM" },
  "CB": { "country": "Cambodia", "flag": "🇰🇭", "source": "US State Dept OFM" },
  "CC": { "country": "Ethiopia", "flag": "🇪🇹", "source": "US State Dept OFM" },
  "CG": { "country": "Marshall Islands", "flag": "🇲🇭", "source": "US State Dept OFM" },
  "CK": { "country": "Namibia", "flag": "🇳🇦", "source": "US State Dept OFM" },
  "CM": { "country": "Micronesia", "flag": "🇫🇲", "source": "US State Dept OFM" },
  "CN": { "country": "International Organization", "source": "US State Dept OFM" },
  "CS": { "country": "Afghanistan", "flag": "🇦🇫", "source": "US State Dept OFM" },
  "CT": { "country": "Bhutan", "flag": "🇧🇹", "source": "US State Dept OFM" },
  "CU": { "country": "Botswana", "flag": "🇧🇼", "source": "US State Dept OFM" },
  "CV": { "country": "Myanmar", "flag": "🇲🇲", "source": "US State Dept OFM" },
  "CW": { "country": "Cameroon", "flag": "🇨🇲", "source": "US State Dept OFM" },
  "CX": { "country": "Burundi", "flag": "🇧🇮", "source": "US State Dept OFM" },
  "CY": { "country": "China", "flag": "🇨🇳", "source": "US State Dept OFM" },
  "DA": { "country": "Colombia", "flag": "🇨🇴", "source": "US State Dept OFM" },
  "DB": { "country": "Costa Rica", "flag": "🇨🇷", "source": "US State Dept OFM" },
  "DC": { "country": "Cuba", "flag": "🇨🇺", "source": "US State Dept OFM" },
  "DD": { "country": "Cyprus", "flag": "🇨🇾", "source": "US State Dept OFM" },
  "DF": { "country": "Dominican Republic", "flag": "🇩🇴", "source": "US State Dept OFM" },
  "DG": { "country": "Ecuador", "flag": "🇪🇨", "source": "US State Dept OFM" },
  "DH": { "country": "Cote d'Ivoire", "flag": "🇨🇮", "source": "US State Dept OFM" },
  "DI": { "country": "South Africa", "flag": "🇿🇦", "source": "US State Dept OFM" },
  "DJ": { "country": "France", "flag": "🇫🇷", "source": "US State Dept OFM" },
  "DK": { "country": "Greece", "flag": "🇬🇷", "source": "US State Dept OFM" },
  "DL": { "country": "India", "flag": "🇮🇳", "source": "US State Dept OFM" },
  "DM": { "country": "Iran", "flag": "🇮🇷", "source": "US State Dept OFM" },
  "DN": { "country": "Denmark", "flag": "🇩🇰", "source": "US State Dept OFM" },
  "DP": { "country": "Bangladesh", "flag": "🇧🇩", "source": "US State Dept OFM" },
  "DR": { "country": "Slovakia", "flag": "🇸🇰", "source": "US State Dept OFM" },
  "DZ": { "country": "Palau", "flag": "🇵🇼", "source": "US State Dept OFM" },
  "FF": { "country": "Antigua and Barbuda", "flag": "🇦🇬", "source": "US State Dept OFM" },
  "FG": { "country": "Central African Republic", "flag": "🇨🇫", "source": "US State Dept OFM" },
  "FH": { "country": "Ireland", "flag": "🇮🇪", "source": "US State Dept OFM" },
  "FJ": { "country": "Lebanon", "flag": "🇱🇧", "source": "US State Dept OFM" },
  "FK": { "country": "Kenya", "flag": "🇰🇪", "source": "US State Dept OFM" },
  "FL": { "country": "Liberia", "flag": "🇱🇷", "source": "US State Dept OFM" },
  "FM": { "country": "Libya", "flag": "🇱🇾", "source": "US State Dept OFM" },
  "FN": { "country": "Malta", "flag": "🇲🇹", "source": "US State Dept OFM" },
  "FP": { "country": "Morocco", "flag": "🇲🇦", "source": "US State Dept OFM" },
  "FR": { "country": "Philippines", "flag": "🇵🇭", "source": "US State Dept OFM" },
  "FS": { "country": "Netherlands", "flag": "🇳🇱", "source": "US State Dept OFM" },
  "FT": { "country": "Qatar", "flag": "🇶🇦", "source": "US State Dept OFM" },
  "FV": { "country": "Sri Lanka", "flag": "🇱🇰", "source": "US State Dept OFM" },
  "FW": { "country": "Holy See", "flag": "🇻🇦", "source": "US State Dept OFM" },
  "FX": { "country": "Sierra Leone", "flag": "🇸🇱", "source": "US State Dept OFM" },
  "FZ": { "country": "Suriname", "flag": "🇸🇷", "source": "US State Dept OFM" },
  "GC": { "country": "Sweden", "flag": "🇸🇪", "source": "US State Dept OFM" },
  "GD": { "country": "Ukraine", "flag": "🇺🇦", "source": "US State Dept OFM" },
  "GG": { "country": "Zambia", "flag": "🇿🇲", "source": "US State Dept OFM" },
  "GN": { "country": "Turkey", "flag": "🇹🇷", "source": "US State Dept OFM" },
  "GP": { "country": "Albania", "flag": "🇦🇱", "source": "US State Dept OFM" },
  "GQ": { "country": "North Korea", "flag": "🇰🇵", "source": "US State Dept OFM" },
  "GX": { "country": "Vanuatu", "flag": "🇻🇺", "source": "US State Dept OFM" },
  "GY": { "country": "Chile", "flag": "🇨🇱", "source": "US State Dept OFM" },
  "HB": { "country": "Tonga", "flag": "🇹🇴", "source": "US State Dept OFM" },
  "HD": { "country": "Argentina", "flag": "🇦🇷", "source": "US State Dept OFM" },
  "HL": { "country": "Saint Lucia", "flag": "🇱🇨", "source": "US State Dept OFM" },
  "HM": { "country": "Andorra", "flag": "🇦🇩", "source": "US State Dept OFM" },
  "HN": { "country": "Mongolia", "flag": "🇲🇳", "source": "US State Dept OFM" },
  "HV": { "country": "Belgium", "flag": "🇧🇪", "source": "US State Dept OFM" },
  "HW": { "country": "Guatemala", "flag": "🇬🇹", "source": "US State Dept OFM" },
  "HX": { "country": "Benin", "flag": "🇧🇯", "source": "US State Dept OFM" },
  "HY": { "country": "Guinea-Bissau", "flag": "🇬🇼", "source": "US State Dept OFM" },
  "HZ": { "country": "Haiti", "flag": "🇭🇹", "source": "US State Dept OFM" },
  "JB": { "country": "Honduras", "flag": "🇭🇳", "source": "US State Dept OFM" },
  "JC": { "country": "Kuwait", "flag": "🇰🇼", "source": "US State Dept OFM" },
  "JD": { "country": "Mauritius", "flag": "🇲🇺", "source": "US State Dept OFM" },
  "JF": { "country": "Nigeria", "flag": "🇳🇬", "source": "US State Dept OFM" },
  "JG": { "country": "Portugal", "flag": "🇵🇹", "source": "US State Dept OFM" },
  "JH": { "country": "Somalia", "flag": "🇸🇴", "source": "US State Dept OFM" },
  "JJ": { "country": "Chad", "flag": "🇹🇩", "source": "US State Dept OFM" },
  "JK": { "country": "Turkey", "flag": "🇹🇷", "source": "US State Dept OFM" },
  "JM": { "country": "Yugoslavia", "source": "US State Dept OFM" },
  "JP": { "country": "Tunisia", "flag": "🇹🇳", "source": "US State Dept OFM" },
  "JQ": { "country": "Togo", "flag": "🇹🇬", "source": "US State Dept OFM" },
  "JS": { "country": "Slovenia", "flag": "🇸🇮", "source": "US State Dept OFM" },
  "JT": { "country": "Croatia", "flag": "🇭🇷", "source": "US State Dept OFM" },
  "JY": { "country": "Cyprus", "flag": "🇨🇾", "source": "US State Dept OFM" },
  "KB": { "country": "Monaco", "flag": "🇲🇨", "source": "US State Dept OFM" },
  "KD": { "country": "Eritrea", "flag": "🇪🇷", "source": "US State Dept OFM" },
  "KG": { "country": "Equatorial Guinea", "flag": "🇬🇶", "source": "US State Dept OFM" },
  "KH": { "country": "Hungary", "flag": "🇭🇺", "source": "US State Dept OFM" },
  "KJ": { "country": "Lithuania", "flag": "🇱🇹", "source": "US State Dept OFM" },
  "KK": { "country": "Fiji", "flag": "🇫🇯", "source": "US State Dept OFM" },
  "KL": { "country": "Jordan", "flag": "🇯🇴", "source": "US State Dept OFM" },
  "KM": { "country": "Jamaica", "flag": "🇯🇲", "source": "US State Dept OFM" },
  "KN": { "country": "Gabon", "flag": "🇬🇦", "source": "US State Dept OFM" },
  "KP": { "country": "Luxembourg", "flag": "🇱🇺", "source": "US State Dept OFM" },
  "KR": { "country": "Malaysia", "flag": "🇲🇾", "source": "US State Dept OFM" },
  "KS": { "country": "Mexico", "flag": "🇲🇽", "source": "US State Dept OFM" },
  "KU": { "country": "Sao Tome and Principe", "flag": "🇸🇹", "source": "US State Dept OFM" },
  "KV": { "country": "Saudi Arabia", "flag": "🇸🇦", "source": "US State Dept OFM" },
  "KW": { "country": "Seychelles", "flag": "🇸🇨", "source": "US State Dept OFM" },
  "KX": { "country": "Sudan", "flag": "🇸🇩", "source": "US State Dept OFM" },
  "LC": { "country": "Venezuela", "flag": "🇻🇪", "source": "US State Dept OFM" },
  "LD": { "country": "Vietnam", "flag": "🇻🇳", "source": "US State Dept OFM" },
  "LG": { "country": "Turkey", "flag": "🇹🇷", "source": "US State Dept OFM" },
  "LH": { "country": "Israel", "flag": "🇮🇱", "source": "US State Dept OFM" },
  "LJ": { "country": "Israel", "flag": "🇮🇱", "source": "US State Dept OFM" },
  "LK": { "country": "European Union", "flag": "🇪🇺", "source": "US State Dept OFM" },
  "LM": { "country": "North Macedonia", "flag": "🇲🇰", "source": "US State Dept OFM" },
  "LR": { "country": "Bosnia and Herzegovina", "flag": "🇧🇦", "source": "US State Dept OFM" },
  "LW": { "country": "Germany", "flag": "🇩🇪", "source": "US State Dept OFM" },
  "MF": { "country": "International Monetary Fund", "source": "US State Dept OFM" },
  "MK": { "country": "Djibouti", "flag": "🇩🇯", "source": "US State Dept OFM" },
  "MN": { "country": "Comoros", "flag": "🇰🇲", "source": "US State Dept OFM" },
  "MP": { "country": "Bahamas", "flag": "🇧🇸", "source": "US State Dept OFM" },
  "MW": { "country": "Maldives", "flag": "🇲🇻", "source": "US State Dept OFM" },
  "NA": { "country": "Oman", "flag": "🇴🇲", "source": "US State Dept OFM" },
  "NB": { "country": "Papua New Guinea", "flag": "🇵🇬", "source": "US State Dept OFM" },
  "NC": { "country": "Paraguay", "flag": "🇵🇾", "source": "US State Dept OFM" },
  "ND": { "country": "Romania", "flag": "🇷🇴", "source": "US State Dept OFM" },
  "NQ": { "country": "Angola", "flag": "🇦🇴", "source": "US State Dept OFM" },
  "NX": { "country": "Malaysia", "flag": "🇲🇾", "source": "US State Dept OFM" },
  "PA": { "country": "Austria", "flag": "🇦🇹", "source": "US State Dept OFM" },
  "PB": { "country": "Barbados", "flag": "🇧🇧", "source": "US State Dept OFM" },
  "PC": { "country": "Belize", "flag": "🇧🇿", "source": "US State Dept OFM" },
  "PD": { "country": "United Kingdom", "flag": "🇬🇧", "source": "US State Dept OFM" },
  "PF": { "country": "Bolivia", "flag": "🇧🇴", "source": "US State Dept OFM" },
  "PG": { "country": "Belarus", "flag": "🇧🇾", "source": "US State Dept OFM" },
  "PK": { "country": "Norway", "flag": "🇳🇴", "source": "US State Dept OFM" },
  "PL": { "country": "Chile", "flag": "🇨🇱", "source": "US State Dept OFM" },
  "PM": { "country": "Brunei", "flag": "🇧🇳", "source": "US State Dept OFM" },
  "PR": { "country": "Argentina", "flag": "🇦🇷", "source": "US State Dept OFM" },
  "PS": { "country": "Zimbabwe", "flag": "🇿🇼", "source": "US State Dept OFM" },
  "PV": { "country": "Republic of the Congo", "flag": "🇨🇬", "source": "US State Dept OFM" },
  "QD": { "country": "Burkina Faso", "flag": "🇧🇫", "source": "US State Dept OFM" },
  "QL": { "country": "St. Kitts and Nevis", "flag": "🇰🇳", "source": "US State Dept OFM" },
  "QM": { "country": "Bulgaria", "flag": "🇧🇬", "source": "US State Dept OFM" },
  "QN": { "country": "Laos", "flag": "🇱🇦", "source": "US State Dept OFM" },
  "QP": { "country": "Latvia", "flag": "🇱🇻", "source": "US State Dept OFM" },
  "QQ": { "country": "Lesotho", "flag": "🇱🇸", "source": "US State Dept OFM" },
  "QR": { "country": "Malawi", "flag": "🇲🇼", "source": "US State Dept OFM" },
  "QS": { "country": "Mozambique", "flag": "🇲🇿", "source": "US State Dept OFM" },
  "QT": { "country": "New Zealand", "flag": "🇳🇿", "source": "US State Dept OFM" },
  "QU": { "country": "Nicaragua", "flag": "🇳🇮", "source": "US State Dept OFM" },
  "QV": { "country": "Niger", "flag": "🇳🇪", "source": "US State Dept OFM" },
  "QW": { "country": "Poland", "flag": "🇵🇱", "source": "US State Dept OFM" },
  "QX": { "country": "Pakistan", "flag": "🇵🇰", "source": "US State Dept OFM" },
  "QY": { "country": "Yemen", "flag": "🇾🇪", "source": "US State Dept OFM" },
  "QZ": { "country": "Indonesia", "flag": "🇮🇩", "source": "US State Dept OFM" },
  "RB": { "country": "Rwanda", "flag": "🇷🇼", "source": "US State Dept OFM" },
  "RC": { "country": "St. Vincent and the Grenadines", "flag": "🇻🇨", "source": "US State Dept OFM" },
  "RD": { "country": "Senegal", "flag": "🇸🇳", "source": "US State Dept OFM" },
  "RL": { "country": "Uruguay", "flag": "🇺🇾", "source": "US State Dept OFM" },
  "RV": { "country": "San Marino", "flag": "🇸🇲", "source": "US State Dept OFM" },
  "SF": { "country": "Czech Republic", "flag": "🇨🇿", "source": "US State Dept OFM" },
  "SG": { "country": "Israel", "flag": "🇮🇱", "source": "US State Dept OFM" },
  "ST": { "country": "Dominica", "flag": "🇩🇲", "source": "US State Dept OFM" },
  "TF": { "country": "Algeria", "flag": "🇩🇿", "source": "US State Dept OFM" },
  "TG": { "country": "Canada", "flag": "🇨🇦", "source": "US State Dept OFM" },
  "TH": { "country": "Egypt", "flag": "🇪🇬", "source": "US State Dept OFM" },
  "TK": { "country": "Liechtenstein", "flag": "🇱🇮", "source": "US State Dept OFM" },
  "TL": { "country": "El Salvador", "flag": "🇸🇻", "source": "US State Dept OFM" },
  "TM": { "country": "Iceland", "flag": "🇮🇸", "source": "US State Dept OFM" },
  "TN": { "country": "Nepal", "flag": "🇳🇵", "source": "US State Dept OFM" },
  "TP": { "country": "Mauritania", "flag": "🇲🇷", "source": "US State Dept OFM" },
  "TQ": { "country": "Mali", "flag": "🇲🇱", "source": "US State Dept OFM" },
  "TR": { "country": "Italy", "flag": "🇮🇹", "source": "US State Dept OFM" },
  "TS": { "country": "Iraq", "flag": "🇮🇶", "source": "US State Dept OFM" },
  "TT": { "country": "Guyana", "flag": "🇬🇾", "source": "US State Dept OFM" },
  "TU": { "country": "Guinea", "flag": "🇬🇳", "source": "US State Dept OFM" },
  "TV": { "country": "Ghana", "flag": "🇬🇭", "source": "US State Dept OFM" },
  "TW": { "country": "Gambia", "flag": "🇬🇲", "source": "US State Dept OFM" },
  "TX": { "country": "Finland", "flag": "🇫🇮", "source": "US State Dept OFM" },
  "TY": { "country": "Grenada", "flag": "🇬🇩", "source": "US State Dept OFM" },
  "TZ": { "country": "Peru", "flag": "🇵🇪", "source": "US State Dept OFM" },
  "UA": { "country": "Bahrain", "flag": "🇧🇭", "source": "US State Dept OFM" },
  "UF": { "country": "Estonia", "flag": "🇪🇪", "source": "US State Dept OFM" },
  "UH": { "country": "Spain", "flag": "🇪🇸", "source": "US State Dept OFM" },
  "UX": { "country": "Trinidad and Tobago", "flag": "🇹🇹", "source": "US State Dept OFM" },
  "VF": { "country": "Thailand", "flag": "🇹🇭", "source": "US State Dept OFM" },
  "VG": { "country": "Tanzania", "flag": "🇹🇿", "source": "US State Dept OFM" },
  "VH": { "country": "Switzerland", "flag": "🇨🇭", "source": "US State Dept OFM" },
  "VJ": { "country": "Brazil", "flag": "🇧🇷", "source": "US State Dept OFM" },
  "VK": { "country": "Singapore", "flag": "🇸🇬", "source": "US State Dept OFM" },
  "VL": { "country": "Eswatini", "flag": "🇸🇿", "source": "US State Dept OFM" },
  "VM": { "country": "Nauru", "flag": "🇳🇷", "source": "US State Dept OFM" },
  "WB": { "country": "United Arab Emirates", "flag": "🇦🇪", "source": "US State Dept OFM" },
  "WD": { "country": "South Korea", "flag": "🇰🇷", "source": "US State Dept OFM" },
  "WM": { "country": "Samoa", "flag": "🇼🇸", "source": "US State Dept OFM" },
  "WZ": { "country": "United Kingdom", "flag": "🇬🇧", "source": "US State Dept OFM" },
  "XA": { "country": "Bangladesh", "flag": "🇧🇩", "source": "US State Dept OFM" },
  "XC": { "country": "Fiji", "flag": "🇫🇯", "source": "US State Dept OFM" },
  "XD": { "country": "Myanmar", "flag": "🇲🇲", "source": "US State Dept OFM" },
  "XE": { "country": "Ghana", "flag": "🇬🇭", "source": "US State Dept OFM" },
  "XF": { "country": "Turkey", "flag": "🇹🇷", "source": "US State Dept OFM" },
  "XG": { "country": "Norway", "flag": "🇳🇴", "source": "US State Dept OFM" },
  "XZ": { "country": "Australia", "flag": "🇦🇺", "source": "US State Dept OFM" },
  "YA": { "country": "Armenia", "flag": "🇦🇲", "source": "US State Dept OFM" },
  "YG": { "country": "Georgia", "flag": "🇬🇪", "source": "US State Dept OFM" },
  "YJ": { "country": "Tajikistan", "flag": "🇹🇯", "source": "US State Dept OFM" },
  "YK": { "country": "Kazakhstan", "flag": "🇰🇿", "source": "US State Dept OFM" },
  "YM": { "country": "Moldova", "flag": "🇲🇩", "source": "US State Dept OFM" },
  "YR": { "country": "Russia", "flag": "🇷🇺", "source": "US State Dept OFM" },
  "YT": { "country": "Turkmenistan", "flag": "🇹🇲", "source": "US State Dept OFM" },
  "YY": { "country": "Kyrgyzstan", "flag": "🇰🇬", "source": "US State Dept OFM" },
  "YZ": { "country": "Azerbaijan", "flag": "🇦🇿", "source": "US State Dept OFM" }
};

var SPOTTED_CODES = {
  "GK": { "country": "Unknown", "source": "Spotted" }
};

var PLATE_PREFIXES = { "D": "Diplomat", "S": "Staff", "C": "Consul" };

function getCountryCode(code) {
  code = code.toUpperCase().replace(/[^A-Z]/g, '');
  if (code.length < 2) return null;
  if (code.length >= 3 && PLATE_PREFIXES[code[0]]) {
    return code.substring(1, 3);
  }
  return code.substring(0, 2);
}

function lookupPlate(code) {
  code = code.toUpperCase().replace(/[^A-Z]/g, '');
  if (code.length < 2) return null;

  var prefix = null;
  var countryCode = getCountryCode(code);

  if (code.length >= 3 && PLATE_PREFIXES[code[0]]) {
    prefix = PLATE_PREFIXES[code[0]];
  }

  var entry = OFM_CODES[countryCode] || SPOTTED_CODES[countryCode];
  if (!entry) return null;

  return { prefix: prefix, code: countryCode, country: entry.country, flag: entry.flag || '', source: entry.source, fullCode: code };
}
